languages:
  PHP: true
engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
    - app/**
exclude_paths:
  - app/Console/Kernel.php
  - app/Exceptions/**
  - app/Listeners/ExampleListener.php
  - config/**/*
  - database/**/*
  - public/**/*
  - reports/**/*
  - resources/**/*
  - storage/**/*
  - tests/**/*
  - vendor/**/*
